= {root-project-name} ({project-version})
Maksim Kostromin <daggerok@gmail.com>
{docdatetime}
:doctype: book
:toc: left
:toclevels: 4
:source-highlighter: prettify
:numbered:
:icons: font
:hide-uri-scheme:
:revnumber: {project-version}
:example-caption!:

Travis CI status:
ifdef::backend-html5[image:https://travis-ci.org/daggerok/{root-project-name}.svg?branch=master["Build Status", link={github-url}]]

////
GitLab CI status:
ifdef::backend-html5[image:https://gitlab.com/daggerok/{root-project-name}/badges/master/build.svg["Build Status", link={gitlab-url}]]

BitBucket CI status:
ifdef::backend-html5[image:https://img.shields.io/bitbucket/pipelines/daggerok/{root-project-name}.svg["Build Status", link={bitbucket-url}]]
////

== Introduction

include::../../README.adoc[tags=content]

== Implementation

=== frontend

.add material design to project:
[source,bash]
----
ng add @angular/material
----

.add application components

.configure material design as separed module (`app-angular-material.module.ts` file):
[source,typescript]
----
include::../../frontend/src/app/app-angular-material.module.ts[tags=content]
----

.configure application routes (`app-routing.module.ts` file):
[source,typescript]
----
include::../../frontend/src/app/app-routing.module.ts[tags=content]
----

== Docker

=== frontend

.build frontend application
[source,bash]
----
cd ./frontend

npm i
npm run dist
----

.build docker image based on nginx
[source,bash]
----
docker build -t daggerok/mean-stack:frontend .
----

.run application in docker
[source,bash]
----
docker run -d --rm -p 80:80 --name run-mean-stack-frontend daggerok/mean-stack:frontend
----

.check application is working on http://0.0.0.0/
[source,bash]
----
open http://127.0.0.0/

docker stop run-mean-stack-frontend
----

.finally stop docker container for cleanning up...
[source,bash]
----
docker stop run-mean-stack-frontend
----

== Heroku deployment

=== frontend

.prepare frontend Dockerfile (`Dockerfile.frontend` file):
[source,bash]
----
include::../../Dockerfile.frontend[tags=content]
----

.prepare nginx config template (`docke/default.conf.tpl` file):
[source,bash]
----
include::../../docke/default.conf.tpl
----

.prepare `heroku.yml` file:
[source,bash]
----
include::../../heroku.yml
----

.create heroku application
[source,bash]
----
heroku create daggerok-mean-stack-frontend --stack=container

# output:
Creating ⬢ daggerok-mean-stack-frontend... done
https://daggerok-mean-stack-frontend.herokuapp.com/ | https://git.heroku.com/daggerok-mean-stack-frontend.git
----

.push app
[source,bash]
----
heroku container:push web --app daggerok-mean-stack-frontend

# output:
=== Building web (/private/tmp/mean-stack/frontend/Dockerfile)
Sending build context to Docker daemon  482.3kB
Step 1/3 : FROM nginx:1.15.0-alpine
 ---> bc7fdec94612
Step 2/3 : COPY ./dist/frontend /usr/share/nginx/html
 ---> Using cache
 ---> 5e856eafa25e
Step 3/3 : COPY ./default.conf.nginx /etc/nginx/conf.d/default.conf
 ---> Using cache
 ---> 74cba1b1e198
Successfully built 74cba1b1e198
Successfully tagged registry.heroku.com/daggerok-mean-stack-frontend/web:latest
=== Pushing web (/private/tmp/mean-stack/frontend/Dockerfile)
The push refers to repository [registry.heroku.com/daggerok-mean-stack-frontend/web]
af18e8661629: Pushed
ddb559f4741a: Pushed
951c1d7bace7: Pushed
91295ee17337: Pushed
423678709065: Pushed
cd7100a72410: Pushed
latest: digest: sha256:6714c7deb2ab1a92d83c314a7364c7c5ff32274406ca1fe2e42ee4a9ed203c40 size: 1570
Your image has been successfully pushed. You can now release it with the 'container:release' command.
 ▸    heroku container:push no longer creates a release.
 ▸    Run heroku container:release to create a release with this image.
----

== Links

ifdef::backend-html5[link:./index.pdf[Documentation in PFD format]]

link:https://github.com/daggerok/{root-project-name}[GitHub]

////
link:https://gitlab.com/daggerok/findbugs-example[GitLab]

link:https://bitbucket.com/daggerok/findbugs-example[BitBucket]
////
