= {root-project-name} ({project-version})
Maksim Kostromin <daggerok@gmail.com>
{docdatetime}
:doctype: book
:toc: left
:toclevels: 4
:source-highlighter: prettify
:numbered:
:icons: font
:hide-uri-scheme:
:revnumber: {project-version}
:example-caption!:

Travis CI status:
ifdef::backend-html5[image:https://travis-ci.org/daggerok/{root-project-name}.svg?branch=master["Build Status", link={github-url}]]

////
GitLab CI status:
ifdef::backend-html5[image:https://gitlab.com/daggerok/{root-project-name}/badges/master/build.svg["Build Status", link={gitlab-url}]]

BitBucket CI status:
ifdef::backend-html5[image:https://img.shields.io/bitbucket/pipelines/daggerok/{root-project-name}.svg["Build Status", link={bitbucket-url}]]
////

== Introduction

include::../../README.adoc[tags=content]

== Implementation

=== frontend

.add material design to project:
[source,bash]
----
ng add @angular/material
----

.add application components

.configure material design as separed module (`app-angular-material.module.ts` file):
[source,javascript]
----
include::../../frontend/src/app/app-angular-material.module.ts[tags=content]
----

.configure application routes (`app-routing.module.ts` file):
[source,javascript]
----
include::../../frontend/src/app/app-routing.module.ts[tags=content]
----

== Docker

=== frontend

.build frontend application
[source,bash]
----
npm i
npm run dist
----

.build docker image based on nginx
[source,bash]
----
cp -Rf ./.dockerignore.frontend ./.dockerignore
docker build -f Dockerfile.frontend -t daggerok/mean-stack:frontend ./frontend
----

.run application in docker
[source,bash]
----
docker run -d --rm -p 80:80 -e "PORT=80" --name run-mean-stack-frontend daggerok/mean-stack:frontend
----

.check application is working on http://0.0.0.0/
[source,bash]
----
open http://127.0.0.0/
----

.finally stop docker container for cleanning up...
[source,bash]
----
docker stop run-mean-stack-frontend
----

== Heroku deployment

=== frontend

==== prepare nginx in docker for heroku

TIP: Idea is very simple:
     as far nginx doesn't support environment variables,
     but heroku is required ENV `$PORT` to be used,
     we can create nginx default.conf template
     and during build or bootstrap generate and replace it in nginx.
     see `Dockerfile.frontend` for derails

NOTE: We will be using `Dockerfile.frontend-build` file instead.
      This file also contains instructions for project build using npm.

.prepare frontend Dockerfile (`Dockerfile.frontend` file):
[source,bash]
----
include::../../Dockerfile.frontend[tags=content]
----
//include::../../Dockerfile.frontend-build[tags=content]

.prepare nginx config template (`docke/default.conf.tpl` file) to be used by Dockerfil during image build:
[source,lua]
----
include::../../docker/default.conf.tpl[]
----

==== prepare heroku config

.prepare `heroku.yml` file:
[source,yaml]
----
include::../../heroku.yml.frontend[]
----

==== create and deploy heroku app

.build app
[source,bash]
----
cd ./frontend
npm i
npm run dist
cd ..
----

.create heroku application
[source,bash]
----
heroku create daggerok-mean-stack-frontend --stack=container

# output:

Creating ⬢ daggerok-mean-stack-frontend... done, stack is container
https://daggerok-mean-stack-frontend.herokuapp.com/ | https://git.heroku.com/daggerok-mean-stack-frontend.git
----

.push app
[source,bash]
----
cp -Rf ./.gitignore.heroku ./.gitignore
cp -Rf ./heroku.yml.frontend ./heroku.yml
cp -Rf ./.dockerignore.frontend ./.dockerignore

git add .
git commit -am "Deploy heroku app."
git push heroku master
----
//cp -Rf ./heroku.yml.frontend-build ./heroku.yml
//cp -Rf ./.dockerignore.frontend-build ./.dockerignore

== docker can also build...

NOTE: Here we will be using `Dockerfile.frontend-build` file instead.
      This file also contains instructions for project build using npm.
      We wanna simply delegate everything to `git push heroku master` instruction

.prepare frontend-build Dockerfile (`Dockerfile.frontend-build` file):
[source,bash]
----
include::../../Dockerfile.frontend-build[tags=content]
----

.build everything run and test...
[source,bash]
----
docker build --rm --no-cache -f Dockerfile.frontend-build -t daggerok/mean-stack-frontend-build .
docker run -d --rm --name run-mean-stack-frontend-build -p 80:80 daggerok/mean-stack-frontend-build
open http://0.0.0.0/
docker stop run-mean-stack-frontend-build
----

=== same, but build in heroku

NOTE: Here, we wanna simply delegate everything to `git push heroku master` instruction

.prepare `heroku.yml` file:
[source,yaml]
----
include::../../heroku.yml.frontend-build[]
----

[source,bash]
////
cp -Rf ./heroku.yml.frontend-build ./heroku.yml
cp -Rf ./.dockerignore.frontend-build ./.dockerignore
////
----
cp -Rf ./.gitignore.local ./.gitignore
cp -Rf ./heroku.yml.frontend-build ./heroku.yml
cp -Rf ./.dockerignore.frontend-build ./.dockerignore
git add .
git commit -am "Deploy heroku app."
git push heroku master
----

== Links

ifdef::backend-html5[link:./index.pdf[Documentation in PFD format]]

link:https://github.com/daggerok/{root-project-name}[GitHub]

link:https://asciidoctor.org/docs/user-manual/#source-code-blocks[asciidoctor reference...]

////
link:https://gitlab.com/daggerok/findbugs-example[GitLab]

link:https://bitbucket.com/daggerok/findbugs-example[BitBucket]
////
