= {root-project-name} ({project-version})
Maksim Kostromin <daggerok@gmail.com>
{docdatetime}
:doctype: book
:toc: left
:toclevels: 4
:source-highlighter: prettify
:numbered:
:icons: font
:hide-uri-scheme:
:revnumber: {project-version}
:example-caption!:

Travis CI status:
ifdef::backend-html5[image:https://travis-ci.org/daggerok/{root-project-name}.svg?branch=master["Build Status", link={github-url}]]

////
GitLab CI status:
ifdef::backend-html5[image:https://gitlab.com/daggerok/{root-project-name}/badges/master/build.svg["Build Status", link={gitlab-url}]]

BitBucket CI status:
ifdef::backend-html5[image:https://img.shields.io/bitbucket/pipelines/daggerok/{root-project-name}.svg["Build Status", link={bitbucket-url}]]
////

== Introduction

include::../../README.adoc[tags=content]

== Implementation

=== frontend

.add material design to project:
[source,bash]
----
ng add @angular/material
----

.add application components

.configure material design as separed module (`app-angular-material.module.ts` file):
[source,typescript]
----
include::../../frontend/src/app/app-angular-material.module.ts[tags=content]
----

.configure application routes (`app-routing.module.ts` file):
[source,typescript]
----
include::../../frontend/src/app/app-routing.module.ts[tags=content]
----

== Docker

=== frontend

.build frontend application
[source,bash]
----
npm i
npm run dist
----

.build docker image based on nginx
[source,bash]
----
docker build -f Dockerfile.frontend -t daggerok/mean-stack:frontend ./frontend
----

.run application in docker
[source,bash]
----
docker run -d --rm -p 80:80 -e "PORT=80" --name run-mean-stack-frontend daggerok/mean-stack:frontend
----

.check application is working on http://0.0.0.0/
[source,bash]
----
open http://127.0.0.0/
----

.finally stop docker container for cleanning up...
[source,bash]
----
docker stop run-mean-stack-frontend
----

== Heroku deployment

=== frontend

==== heroku + nginx (in docker)

TIP: Idea is simple: as far nginx doesn;t support environment variables,
     but heroku is required ENV `$PORT` to be used,
     we can create nginx default.conf template
     and during build or bootstrap generate and replace it in nginx.
     see `Dockerfile.frontend` for derails

.prepare frontend Dockerfile (`Dockerfile.frontend` file):
[source,bash]
----
include::../../Dockerfile.frontend[tags=content]
----

.prepare nginx config template (`docke/default.conf.tpl` file):
[source,bash]
----
include::../../docker/default.conf.tpl[]
----

.prepare `heroku.yml` file:
[source,bash]
----
include::../../heroku.yml[]
----

.create heroku application
[source,bash]
----
heroku create daggerok-mean-stack-frontend --stack=container

# output:
Creating ⬢ daggerok-mean-stack-frontend... done
https://daggerok-mean-stack-frontend.herokuapp.com/ | https://git.heroku.com/daggerok-mean-stack-frontend.git
----

.push app
[source,bash]
----
git add .
git commit -am "Deploy heroku app."
git push heroku master

# output: TODO...
----

== Links

ifdef::backend-html5[link:./index.pdf[Documentation in PFD format]]

link:https://github.com/daggerok/{root-project-name}[GitHub]

////
link:https://gitlab.com/daggerok/findbugs-example[GitLab]

link:https://bitbucket.com/daggerok/findbugs-example[BitBucket]
////
